export enum GamePlatform {
	MinecraftJava = 1,
	MinecraftBedrock = 2,
	MinecraftOffline = 3,
	Unturned = 4,
	Rust = 5,
	DaysToDie = 6,
	GarrysMod = 7,
	CounterStrikeGlobalOffensive = 8,
	TeamFortress2 = 9,
	Hurtworld = 10,
	ArkSurvivalEvolved = 11,
	SpaceEngineers = 12,
	Atlas = 13,
	GtaV = 14,
	FiveM = 15,
}

export enum GamePlatformLabel {
	MinecraftJava = 'Minecraft: Java Edition',
	MinecraftBedrock = 'Minecraft (Bedrock)',
	MinecraftOffline = 'Minecraft Offline',
	Unturned = 'Unturned',
	Rust = 'Rust',
	DaysToDie = '7 Days to Die',
	GarrysMod = 'Garrys Mod',
	CounterStrikeGlobalOffensive = 'Counter-Strike: Global Offensive',
	TeamFortress2 = 'Team Fortress 2',
	Hurtworld = 'Hurtworld',
	ArkSurvivalEvolved = 'ARK: Survival Evolved',
	SpaceEngineers = 'Space Engineers',
	Atlas = 'ATLAS',
	GtaV = 'GTA V',
	FiveM = 'FiveM',
}
